### ISSUE TITLE
Alpha Checklist

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#170]
This issue is to keep track of Alpha progress and ensure that any existing functionality isn't lost in the rebuild of dropchop in the `alpha` branch.

Currently existing functionality:

- [x] selecting layers updates selection
- [x] change map base tiles
- [x] load from local files
- [x] load from url
- [x] load from gist
- [x] UI selection/unselection for multiple layers (not super tied to this right now)
- [x] open forms with parameters
- [x] execute turf operations
- [x] add new layers into map after turf operation
- [x] save as geojson
- [x] save as shapefile
- [x] completely remove layers
- [x] tests written/re-written
- [x] maintain smooth deployment process
- [x] notifications
- [x] load gist/external source from url parameters `?gist=XXXXXXXX`
- [x] click on features and view attributes

Features for alpha release:

- [x] show available operations once you've selected layers #145 
- [x] ~~view/edit attribute table~~ #165 
- [x] recursively execute on feature collections #91 
- [x] ~~right click for options~~ #142 
- [x] ~~upload shapefiles~~ #10 
- [x] google analytics
- [x] about page `/about.html`
- [x] view extent button #15 
- [ ] show your location (via @jonahadkins) #144 & #171
- [x] handle operations that take multiple geometries that depend on order (i.e `turf-aggregate`)
- [x] begin semantic versioning. Alpha release = `1.0.0`
- [x] updated readme

Nice-to-haves
- [x] rename layers
- [x] ~~figure out how we can deal with turf functions that don't return geometry~~ #80 
- [x] function that runs across a feature collection and turns all features into their own layer
- [x] ~~zip downloads larger than one file~~ #182 
- [x] hide all / show all layers
- [x] load data via overpass api
- [x] duplicate layer
- [x] "loading" feature for any API call #127

**Comment by mapsam** [comment]
Things are coming along nicely! Some current thoughts that I shared with @alukach over slack:

* The move to jQuery pub/sub (with `.toggle()` and `.on()` has been quite helpful - it keeps everything that’s happening in the proper file, instead of losing track of things in the controller. Subscriptions happen where their functions exist, publishings happen from where actions are taken
* Decoupling Dropchop from Leaflet makes things a bit more straightforward - I think the only leaflet utility we are using right now is `L.stamp()`, which is great for tying our layers object to every other representation of layers (i.e. in the map, sidebar, selection, etc.)
* I'll plan on implementing the above features throughout today and tomorrow, with tests & debugging coming later this and next week

Current status view:

![dropchop-alpha-update1](https://cloud.githubusercontent.com/assets/1943001/9833648/e533e306-5953-11e5-9582-7a8042274317.gif)

**Comment by mapsam** [comment]
Save as geojson:

![dropchop-save-geojson](https://cloud.githubusercontent.com/assets/1943001/9834129/452c8124-5962-11e5-928d-4012e6855c64.gif)

**Comment by mapsam** [comment]
Adding an about page:

<img width="815" alt="screen shot 2015-09-12 at 4 51 44 pm" src="https://cloud.githubusercontent.com/assets/1943001/9834458/9b4020e6-596e-11e5-8813-8b3d4a8df14d.png">

**Comment by mapsam** [comment]
View extent & load from gist/url are back on track!

![dropchop-extent](https://cloud.githubusercontent.com/assets/1943001/9834906/a043bc22-5984-11e5-953c-bd0bc2a99343.gif)

Re-used much of the code for url/gist loading from @alukach - the big difference here is including the execution/get request/callback all within the `ops.file.dropchop.js` file, rather than separating them.

![dropchop-gist-load](https://cloud.githubusercontent.com/assets/1943001/9834925/7efde910-5985-11e5-9720-99465d10c7f2.gif)

**Comment by mapsam** [comment]
Toggle all layers is now a feature!

![dropchop-toggle-all](https://cloud.githubusercontent.com/assets/1943001/9835450/a54aae30-59a0-11e5-9887-73afab4af51c.gif)

**Comment by mapsam** [comment]
Loading data from the url is back

![dropchop-loadurlparams](https://cloud.githubusercontent.com/assets/1943001/9837160/365faa84-59eb-11e5-9385-8786147eb566.gif)

**Comment by mapsam** [comment]
Building in a switch/radio button parameter that allows you to specify which layer you want to be added first. This is important for turf operations that require one type of geometry first, followed by a different one. The example below is for `turf-within`:

![dropchop-orderisimportant](https://cloud.githubusercontent.com/assets/1943001/9837572/6d3fc950-59f8-11e5-83a5-7e43be40b90a.gif)

**Comment by mapsam** [comment]
New layers have a `.layer-new` class on them for `3000 ms` for visual effect:

![dropchop-newlayercolor](https://cloud.githubusercontent.com/assets/1943001/9837615/1792e896-59fa-11e5-8afd-705f0d81db9a.gif)

**Comment by mapsam** [comment]
duplicate layer

![dropchop-duplicatelayer](https://cloud.githubusercontent.com/assets/1943001/9856216/380fcaa2-5ac8-11e5-8948-83051a4c94d9.gif)

**Comment by mapsam** [comment]
Expand `FeatureCollection` into multiple features *and* compress features into a single `FeatureCollection`

![dropchop-expandcompress](https://cloud.githubusercontent.com/assets/1943001/9860074/c690dd96-5ade-11e5-9da4-9c6e1c2a426d.gif)

**Comment by mapsam** [comment]
Adding icons for geometry types and an "example data" link that is loaded with `?gist=XXXXXXXX`

![dropchop-exampledata](https://cloud.githubusercontent.com/assets/1943001/9868671/8f05df50-5b30-11e5-84cf-bb846433e03e.gif)

**Comment by mapsam** [comment]
rename layers:

![dropchop-rename](https://cloud.githubusercontent.com/assets/1943001/9897918/a8af75e2-5c02-11e5-87d2-c17600b8e430.gif)

**Comment by mapsam** [comment]
Popups that contain a table of all properties:

<img width="427" alt="screen shot 2015-09-26 at 10 42 20 pm" src="https://cloud.githubusercontent.com/assets/1943001/10121483/d2f50ef4-64a2-11e5-8ade-af4a53578720.png">

**Comment by mapsam** [comment]
Alright, other than adding in @jonahadkins's "my location" feature, I'm calling the new features complete on the `alpha` repo! Time to finish up writing the tests and smooth out deployment with codeship.io. Feeling almost ready for the NACIS release!

:dancer:

**Comment by mapsam** [comment]
Woops.
